services:
  database:
    image: 'postgres:16.0-alpine3.18'
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: infra/dockerfile
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      NODE_ENV: development
    ports:
      - '3000:3000'
    depends_on:
      - database
      - redis
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt:ro
    depends_on:
      - app

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  postgres_data:
