FROM node:20.0.0-alpine3.15
WORKDIR /app
COPY ../package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
# TODO: o APP esta reinicindo varias vezes 2025-03-14 09:46:08 You are using Node.js 18.0.0. For Next.js, Node.js version "^18.18.0 || ^19.8.0 || >= 20.0.0" is required.
# Add a health check to monitor the application's status
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 CMD curl -f http://localhost:3000/ || exit 1

CMD ["npm", "start"]
